### PR TITLE
Fixes update record method

### LINKED ISSUE #9: Blanket not updating new knackhq fields
I did some testing and found out that the fields never change within knackhq. I need to figure out how to Put form-data through blanket. 

Blanket::Put always returns a copy of the object. So the tests pass but if I test if the value changes, then the test fails.

### PR DESCRIPTION
**Pull request by michaelachrisco**
Fixes #9

### CODE REVIEW

**Comment by michaelachrisco** [comment]
@josephbridgwaterrowe  Please review.

File: lib/knackhq/client.rb [hunk 1]
```diff
@@ -16,13 +16,13 @@ def objects
       hash_request = request
                      .objects
                      .get
-                     .to_h[:objects]
+                     .payload[0].to_h[:objects]
```
Comment (josephbridgwaterrowe) [inline lib/knackhq/client.rb]: Is the payload attribute new to the latest Blanket version?

I believe that this code could also be dried up a bit if you're interested.

Comment (michaelachrisco) [inline lib/knackhq/client.rb]: Yes payload is new. Ill dry this up.

**Comment by michaelachrisco** [comment]
If this is good, I will rebase.

File: lib/knackhq/client.rb [hunk 2]
```diff
@@ -48,10 +48,9 @@ def records_by_page(object, page_number)
...
-                     .to_h
-      return [] if hash_request.empty?
-      transform_hash_keys = hash_request[:records]
-      symbolize_hash_keys!(transform_hash_keys)
+      payload = payload_hash(hash_request)
+      return [] if payload.empty?
+      payload[:records]
     end
 
     def records_info(object)
```
Comment (josephbridgwaterrowe) [inline lib/knackhq/client.rb]: What does this method return?

Comment (michaelachrisco) [inline lib/knackhq/client.rb]: Sorry just saw the comment. It returns a [hash] with the records information. For example, a record might have multiple fields, page numbers, etc.. I wanted to make sure that what was returned was an array (as is standard within the rest of our app). 
Example: 

``` Ruby
[{:total_pages=>999, :current_page=>1, :total_records=>999}]
```

Comment (josephbridgwaterrowe) [inline lib/knackhq/client.rb]: OK, thanks. What benefit does this provide over just a normal object query?

Comment (michaelachrisco) [inline lib/knackhq/client.rb]:
``` Ruby
# Returns only object records
records(object)
[{:name => 'name_1, :id => 'hfhdh1223'},{...n-1}]

# Returns object info
records_info(object)
[{:total_pages=>999, :current_page=>1, :total_records=>1000000}]
```

This enables a separation between the info of all the knackhq records and the records themselves. We don't care that record #30 is in the `current page=1` of `total_records=100`  first batch of received records from knackhq in our interactor, we only care that it is mirrored.  And if we do, then we have the method `records_by_page` which returns the objects' records by batches of 500 (each page has 500 'rows' or records).

Comment (josephbridgwaterrowe) [inline lib/knackhq/client.rb]: But the Knach API is still performing the same query? And the non info version still returns the same info as well as the objects?

Comment (michaelachrisco) [inline lib/knackhq/client.rb]: Appologies I was being misleading. 
The Knackhq client returns `records(object)` with Knackhqs' default of 25 rows per page. 

The records_info(object) is explicit in the amount of rows (500) returned and therefore can give an accurate amount of pages for other applications to consume.

Comment (michaelachrisco) [inline lib/knackhq/client.rb]: If you recall, my idea before was to return an Ruby object (call it KnackhqObject) that would have a name, multiple fields, and records.

For example:

``` Ruby
Knackhq::Objects.new(app_id, app_key)
Returns:

[KnackhqObject(:knack_id => '1234',  :fields => {field_1=>{:feild_info....},:field_2=>{..}...}, :records=>[...], :total_records => 1000)....]
```

I think we decided against it for some reason. It would produce a bit more complexity but would return a model rather than a collection of methods. Honestly, It would make a good 1.0 feature set but may not be good just now.

Right now, the current feature set works with the HayApp. Unless there is something I am missing?

Comment (michaelachrisco) [inline lib/knackhq/client.rb]: I suppose I could also remove the three records methods and combine them into one master record method:

``` Ruby
    def records(object, options ={})
      options[:rows_per_page] ||= 25
      options[:page_number] || 1
      hash_request = ...
    end
# which will return
{:total_pages=>999, :current_page=>1, :total_records=>1000000 :records=>[record1, record2, etc..]}
```

Comment (josephbridgwaterrowe) [inline lib/knackhq/client.rb]: I think thats better personally :).

File: lib/knackhq/client.rb [hunk 3]
```diff
@@ -16,62 +16,64 @@ def objects
...
-      return [] if hash_request.empty?
-      transform_hash_keys = hash_request[:object]['fields']
-      symbolize_hash_keys!(transform_hash_keys)
+      hash_request = request.objects.get(key)
+      payload = payload_hash(hash_request)
+      translate_payload(payload) { payload[:object][:fields] }
     end
 
     def fields(object)
       hash_request = request_object(object, :fields)
```
Comment (josephbridgwaterrowe) [inline lib/knackhq/client.rb]: May I suggest replacing this with a direct call to request since the request_object only appears to be used once.

Comment (michaelachrisco) [inline lib/knackhq/client.rb]: Thanks. That was a deprecated method.

**Comment by michaelachrisco** [comment]
Rebased and ready.

File: lib/knackhq/client.rb [hunk 4]
```diff
@@ -16,62 +16,64 @@ def objects
...
+      page_number = options[:page_number] || 1
+        hash_request = request
+                       .objects(object)
+                       .records
+                       .get(:params => { :page => page_number,
+                                         :rows_per_page => rows_per_page })
+      payload = payload_hash(hash_request)
+      translate_payload(payload) { payload }
     end
+    #
```
Comment (josephbridgwaterrowe) [inline lib/knackhq/client.rb]: :gun:

File: lib/knackhq/client.rb [hunk 5]
```diff
@@ -70,8 +54,8 @@ def update_record(object, knackhq_id, json)
                      .objects(object)
                      .records(knackhq_id)
                      .put(:body => json)
-                     .to_h
-      !hash_request.empty?
+      payload = payload_hash(hash_request)
+      translate_payload(payload) { payload }
```
Comment (josephbridgwaterrowe) [inline lib/knackhq/client.rb]: Correct me if I'm wrong but this will now return an array?

Comment (michaelachrisco) [inline lib/knackhq/client.rb]: Yes. This behavior made the method easy to test. When we had the depreciated Blanket gem, the output was always the same, so we could never test to see if the object has changed, only that the object was in the database. Ill change this behavior to return true/false as we discussed before.

**Comment by josephbridgwaterrowe** [comment]
Rebase and I will merge.

**Comment by michaelachrisco** [comment]
Rebased and ready to go.
